#########################
# project configuration #
#########################

# C++ project
language: cpp
dist: trusty
sudo: required

################
# build matrix #
################

matrix:
  include:
  # OSX / Clang
  - os: osx
    osx_image: xcode9.4

  - os: osx
    osx_image: xcode10.2

  # Linux / GCC
  - os: linux
    compiler: gcc
    env: MATRIX_EVAL="CXX=g++-7 && CXXFLAGS=-std=c++17"

    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test' ]
        packages: ['g++-7' ]

  # Linux / Clang
  - os: linux
    compiler: clang
    env: MATRIX_EVAL="CXX=clang++-5.0 CXXFLAGS=-std=c++1z"
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-5.0']
        packages: ['g++-6', 'clang-5.0' ]

################
# build script #
################


before_install:
    - eval "${MATRIX_EVAL}"

script:
  # get CMake and Ninja (only for systems with brew - macOS)
  - |
     if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
       brew update
       brew install openssl@1.1
     fi

  # show OS/compiler version
  - uname -a
  - $CXX --version

  # compile and execute unit tests
  - mkdir -p build && cd build
  - cmake .. ${CMAKE_OPTIONS} && make
  - ctest -C Release -V -j
